---
# CentOS tasks file for ansible-role-elevate

- name: "Swap the CentOS 7 Base repo to the AlmaLinux ELevate repo"
  get_url:
    url: https://el7.repo.almalinux.org/centos/CentOS-Base.repo
    dest: /etc/yum.repos.d/CentOS-Base.repo
    mode: '0644'
    backup: true
  when:
    - ansible_distribution_major_version == '7'

- name: "Remove packages that will cause issues during Distribution upgrade (yum)"
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - javapackages-tools
    - cmake
    - cmake3
  when:
    - ansible_facts['pkg_mgr'] == 'yum'

- name: "Remove packages that will cause issues during Distribution upgrade (dnf)"
  dnf:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - javapackages-tools
    - cmake
    - cmake3
  when:
    - ansible_facts['pkg_mgr'] == 'dnf'
