---
# DNS tasks file for ansible-role-elevate

- name: "Check if machine has functional DNS nameservers"
  shell: ping -4 -c 1 google.com
  register: dns
  ignore_errors: yes
  changed_when: false

- name: "Set Fact: DNS is functional"
  set_fact:
    functional_dns: true
  when: dns.rc == 0

- name: "Set Fact: DNS is not functional"
  set_fact:
    functional_dns: false
  when: dns.rc != 0

- name: "Collect Device Name of the Management Interface"
  shell: nmcli -t -f NAME connection show --active | grep -i 'eno1'
  register: device
  when: not functional_dns

- name: "Set Fact for Management Interface Device Name"
  set_fact:
    device_name: "{{ device.stdout }}"
  when: not functional_dns

- name: "Collect existing Name Servers for Management Interface"
  shell: nmcli --terse --fields ipv4.dns connection show "{{ device_name }}" | cut -d':' -f2
  register: nameservers
  when: not functional_dns
  changed_when: false

- name: "Set Fact for existing nameservers"
  set_fact:
    nameservers: "{{ nameservers.stdout }}"
  when: not functional_dns
  changed_when: false

- name: "Temporarily add Google Public DNS Servers to Management Interface nameservers"
  shell: nmcli connection modify "{{ device_name }}" ipv4.dns 8.8.8.8,{{ nameservers }}
  when: not functional_dns
  changed_when: false

- name: "Reboot machine"
  reboot:
    reboot_timeout: 14400
  when: not functional_dns
  changed_when: false
