---
# After upgrade tasks file for ansible-role-elevate

- name: "Revert changes to root logins in SSH daemon config"
  lineinfile:
    path: /etc/ssh/sshd_config
    line: 'PermitRootLogin yes'
    state: absent
  when:
    - permit_root_login is defined
    - not permit_root_login
    #- ansible_facts['distribution'] == 'CentOS'
    #- ansible_distribution_major_version == '7'

- name: "Revert changes AllowZoneDrifting in firewalld config"
  replace:
    path: /etc/firewalld/firewalld.conf
    regexp: '^AllowZoneDrifting=no\b'
    replace: 'AllowZoneDrifting=yes'
  when:
    - allow_zone_drifting is defined
    - allow_zone_drifting
    #- allow_zone_drifting is true
