---
# After upgrade tasks file for ansible-role-elevate

- name: "Revert changes to root logins in SSH daemon config"
  lineinfile:
    path: /etc/ssh/sshd_config
    line: 'PermitRootLogin yes'
    state: absent
  when:
    - permit_root_login is defined
    - not permit_root_login

- name: "Revert changes AllowZoneDrifting in firewalld config"
  replace:
    path: /etc/firewalld/firewalld.conf
    regexp: '^AllowZoneDrifting=no\b'
    replace: 'AllowZoneDrifting=yes'
  when:
    - allow_zone_drifting is defined
    - allow_zone_drifting

- name: "Remove 'let skip_defaults_vim=1' from /etc/virc"
  lineinfile:
    path: /etc/virc
    line: "let skip_defaults_vim=1"
    state: absent
    backrefs: no
  when:
    - ansible_distribution_major_version == '8'

#- name: "Remove sslverify in {{ config_file }}"
#  lineinfile:
#    path: "{{ config_file }}"
#    line: 'sslverify=0'
#    state: absent
#  when:
#    - sslverify_value is defined
#    - sslverify_raw == "not_set"

#- name: "Re-Enable sslverify if setting was present in {{ config_file }}"
#  lineinfile:
#    path: "{{ config_file }}"
#    regexp: '^sslverify='
#    line: 'sslverify=1'
#    state: present
#    backrefs: yes
#  when:
#    - sslverify_value is defined
#    - sslverify_value
