---
# After upgrade tasks file for ansible-role-elevate

- name: "Revert changes to root logins in SSH daemon config"
  lineinfile:
    path: /etc/ssh/sshd_config
    line: 'PermitRootLogin yes'
    state: absent
  when: not permit_root_login

- name: "Revert changes AllowZoneDrifting in firewalld config"
  replace:
    path: /etc/firewalld/firewalld.conf
    regexp: '^AllowZoneDrifting=no\b'
    replace: 'AllowZoneDrifting=yes'
  when: not allow_zone_drifting
