---
# CentOS tasks file for ansible-role-elevate

- name: "Swap the CentOS 7 Base repo to the AlmaLinux ELevate repo"
  get_url:
    url: https://el7.repo.almalinux.org/centos/CentOS-Base.repo
    dest: /etc/yum.repos.d/CentOS-Base.repo
    mode: '0644'
    backup: true
  when:
    - ansible_distribution_major_version == '7'

- name: "Set facts for leapp packages"
  set_fact:
    leapp_packages:
      - leapp-upgrade
      - leapp-data-{{ distro }}
