---
# DNS tasks file for ansible-role-elevate

- name: "Check if machine has functional DNS nameservers"
  shell: ping google.com -c 1
  register: dns
  failed_when: dns.rc > 3

- name: "Set Fact for missing or unreachable DNS nameserver"
  set_fact:
    dns: false
  when: dns.rc != 0

- name: "Collect existing Name Servers for Management Interface"
  shell: nmcli --terse --fields ipv4.dns connection show "System eno1" | cut -d':' -f2
  register: nameservers
  when: not dns | bool

- name: "Set Fact for existing nameservers"
  set_fact:
    nameservers: "{{ nameservers.stdout }}"
  when: not dns | bool

- name: "Temporarily add Google Public DNS Servers to Management Interface nameservers"
  shell: nmcli connection modify "System {{ ansible_default_ipv4.interface }}" ipv4.dns 8.8.8.8,{{ nameservers }}
  when: not dns | bool

- name: "Reboot machine"
  reboot:
  when: not dns | bool
