---
# CentOS Fix tasks file for ansible-role-elevate

- name: "Temporarily remove the pata_acpi kernel module"
  shell: rmmod pata_acpi
  ignore_errors: true
  when:
    - ansible_facts['distribution'] == 'CentOS'
    - ansible_distribution_major_version == '7'
