---
# CentOS Fix tasks file for ansible-role-elevate

- name: "Temporarily remove the pata_acpi kernel module"
  shell: rmmod pata_acpi
  ignore_errors: true
  when:
    - ansible_facts['distribution'] == 'CentOS'
    - ansible_distribution_major_version == '7'

- name: "Import PermitRootLogin playbook"
  include_tasks: "PermitRootLogin.yaml"
  when:
    - ansible_facts['distribution'] == 'CentOS'
    - ansible_distribution_major_version == '7'

- name: "Disable AllowZoneDrifting in Firewall Daemon config"
  replace:
    path: /etc/firewalld/firewalld.conf
    regexp: '^AllowZoneDrifting=.*'
    replace: 'AllowZoneDrifting=no'
  when:
    - ansible_distribution_major_version == '8'
