---
# Fix tasks file for ansible-role-elevate

# https://access.redhat.com/solutions/6971716
- name: "Temporarily remove the pata_acpi kernel module"
  shell: rmmod pata_acpi
  ignore_errors: true
  #failed_when: false
  #changed_when: false
  when:
    - ansible_facts['os_family'] == 'RedHat'
    - ansible_distribution_major_version == '7'
