---
# tasks file for ansible-role-elevate

- name: "Import Distribution Prerequisites"
  include_tasks: "{{ ansible_facts['distribution'] }}.yaml"

- name: "Get the major version of the running kernel"
  shell: uname -r | cut -d. -f1
  register: kernel

- name: "Set fact about existing Distribution"
  set_fact:
    existing_version: "{{ ansible_distribution_major_version }}"
    existing_kernel_major_version: "{{ kernel.stdout }}"

- name: "Upgrade the system (yum)"
  yum:
    name: '*'
    state: latest
  register: upgrade
  when:
    - ansible_facts['pkg_mgr'] == 'yum'

- name: "Upgrade the system (dnf)"
  dnf:
    name: '*'
    state: latest
  register: upgrade
  when:
    - ansible_facts['pkg_mgr'] == 'dnf'

- name: "Reboot if packages were upgraded"
  reboot:
  when:
    - upgrade.changed

- name: "Install the ELevate release package"
  yum:
    name: "http://repo.almalinux.org/elevate/elevate-release-latest-el{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present

- name: "Install the leapp packages"
  yum:
    name: "{{ leapp_packages }}"
    state: present

- name: "Import Distribution Fixes"
  include_tasks: "{{ ansible_facts['distribution'] }}-Fixes.yaml"

- name: "Run a Pre-Upgrade check (its going to fail)"
  shell: leapp preupgrade
  register: preupgrade
  failed_when: preupgrade.rc >= 2

- name: "Apply fix for Pre-Upgrade check (CentOS 7)"
  shell: leapp answer --section remove_pam_pkcs11_module_check.confirm=True
  when:
    - ansible_facts['distribution'] == 'CentOS'
    - ansible_distribution_major_version == '7'

- name: "Run a Pre-Upgrade check"
  shell: leapp preupgrade

- name: "Perform the upgrade"
  shell: leapp upgrade
  register: upgrade

- name: "Reboot after the upgrade"
  reboot:
    reboot_timeout: 3600
  when:
    - upgrade.changed

- name: "Remove exclusion from yum configuration file"
  shell: sed -i '/^exclude=/Id' /etc/yum.conf
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: "Remove Legacy packages after upgrade (yum)"
  yum:
    name: "*el{{ existing_version }}*"
    state: latest
  register: upgrade
  vars:
    ansible_python_interpreter: /usr/bin/python3
  when:
    - ansible_facts['pkg_mgr'] == 'yum'

- name: "Remove Legacy packages after upgrade (dnf)"
  dnf:
    name: "*el{{ existing_version }}*"
    state: latest
  register: upgrade
  vars:
    ansible_python_interpreter: /usr/bin/python3
  when:
    - ansible_facts['pkg_mgr'] == 'dnf'

- name: "Remove bootloader entries for Legacy kernels"
  shell: find /boot/loader/entries/ -type f -name "*-{{ existing_kernel_major_version }}.*" -delete
  vars:
    ansible_python_interpreter: /usr/bin/python3
