---
# tasks file for ansible-role-elevate

- name: "Import Distribution Prerequisites"
  include_tasks: "{{ ansible_facts['distribution'] }}.yaml"

- name: "Upgrade the system (yum)"
  yum:
    name: '*'
    state: latest
  register: upgrade
  when:
    - ansible_facts['pkg_mgr'] == 'yum'

- name: "Reboot if packages were upgraded"
  reboot:
  when:
    - upgrade.changed

- name: "Install the ELevate release package"
  yum:
    name: "http://repo.almalinux.org/elevate/elevate-release-latest-el{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present

- name: "Install the leapp packages"
  yum:
    name: "{{ leapp_packages }}"
    state: present

- name: "Run a Pre-Upgrade check (its going to fail)"
  shell: leapp preupgrade
  register: preupgrade
  failed_when: preupgrade.rc >= 2

- name: "Apply fix for Pre-Upgrade check (CentOS 7)"
  shell: leapp answer --section remove_pam_pkcs11_module_check.confirm=True
  when:
    - ansible_facts['distribution'] == 'CentOS'
    - ansible_distribution_major_version == '7'

- name: "Run a Pre-Upgrade check"
  shell: leapp preupgrade
  register: preupgrade

- name: "Perform the upgrade"
  shell: leapp upgrade
  when:
    - preupgrade.changed
