---
# OpenVPN upgrade tasks file for ansible-role-elevate

- name: "Copy OpenVPN configs to /etc/openvpn/client directory"
  copy:
    src: /etc/openvpn/
    dest: /etc/openvpn/client/
    remote_src: true
  when:
    - ansible_distribution_major_version == '8'

- name: "Cleanup OpenVPN config directories"
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/openvpn/client/client
    - /etc/openvpn/client/server
  #when:
  #  - ansible_distribution_major_version == '8'

- name: "Create an archive of the OpenVPN configuration files to the root home directory"
  archive:
    path: /etc/openvpn/client/
    dest: /root/openvpn.zip
    format: zip
  ignore_errors: true
