---
# OpenVPN upgrade tasks file for ansible-role-elevate

- name: "Collect version of currently installed OpenVPN client"
  shell: openvpn --version | head -n 1 | awk '{ print $2 }'
  register: output
  failed_when: output.rc != 0
  changed_when: false

- name: "Set fact for installed OpenVPN version"
  set_fact:
    openvpn_installed: true
    openvpn_version: "{{ output.stdout }}"
    new_version: "2.5.11"
  when:
    output.rc == 0

- name: "Copy OpenVPN configs to /etc/openvpn/client directory"
  copy:
    src: /etc/openvpn/
    dest: /etc/openvpn/client/
    remote_src: true
  when:
    - openvpn | bool
    - existing_major_version == '7'

- name: "Cleanup OpenVPN config directories"
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/openvpn/client/client
    - /etc/openvpn/client/server
  when:
    - openvpn | bool
    - existing_major_version == '7'

- name: "Find any OpenVPN Certificate and Private Key files in /etc/openvpn/client/"
  find:
    paths: /etc/openvpn/client/
    use_regex: false
    file_type: file
  register: files
  when:
    - openvpn | bool
    - existing_major_version == '7'

- name: "Set permissions on the OpenVPN Certificate and Private Key file"
  file:
    path: "{{ item.path }}"
    mode: '0600'
    owner: root
    group: root
  loop: "{{ files.files }}"
  when:
    - openvpn | bool
    - existing_major_version == '7'

# Fix from - https://unix.stackexchange.com/questions/742929/openvpn-private-key-password-being-requested
- name: "Enable legacy_sect provider in /etc/pki/tls/openssl.cnf"
  replace:
    path: /etc/pki/tls/openssl.cnf
    regexp: '{{ item.regexp }}'
    replace: '{{ item.replace }}'
  loop:
    - regexp: '^##(legacy.*)'
      replace: '\1'
    - regexp: '^##(\[legacy.*)'
      replace: '\1'
    - regexp: '^##(activate.*)'
      replace: '\1'
  when:
    - openvpn | bool
    - existing_major_version == '8'

# Fix from - https://www.reddit.com/r/PrivateInternetAccess/comments/j1iyl7/openvpn_client_no_longer_connects_cipher_not/
- name: "Add a Data Cipher to the OpenVPN config"
  lineinfile:
    path: /etc/openvpn/client/client.conf
    line: data-ciphers AES-256-CBC
    insertafter: EOF
    state: present
  when:
    - openvpn | bool
    - new_version is version(openvpn_version, '>=')
    - existing_major_version == '8'

- name: "Create an archive of the OpenVPN configuration files to the root home directory"
  archive:
    path: /etc/openvpn/client/
    dest: /root/openvpn.zip
    format: zip
  ignore_errors: true
  when:
    - openvpn | bool