---
# Pre-Upgrade tasks file for ansible-role-elevate

- name: "Import Distribution Prerequisites"
  include_tasks: "{{ ansible_facts['distribution'] }}.yaml"

- name: "Set facts about existing Distribution"
  set_fact:
    existing_distribution: "{{ ansible_facts['distribution'] }}"
    existing_version: "{{ ansible_distribution_version }}"
    existing_major_version: "{{ ansible_distribution_major_version }}"
    existing_kernel_major_version: "{{ ansible_kernel[0] }}"

- name: "Recursively remove any files from the /var/log/leapp directory"
  ansible.builtin.file:
    path: /var/log/leapp
    state: absent

- name: "Remove any left-over packages that cause issues during Distribution upgrade (yum)"
  yum:
    name: "rocky-logos"
    state: absent
  when:
    - ansible_facts['pkg_mgr'] == 'yum'

- name: "Remove any left-over packages that cause issues during Distribution upgrade (dnf)"
  dnf:
    name: "rocky-logos"
    state: absent
  when:
    - ansible_facts['pkg_mgr'] == 'dnf'

- name: "Install the ELevate release package"
  yum:
    name: "http://repo.almalinux.org/elevate/elevate-release-latest-el{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present

- name: "Install the leapp upgrade package"
  yum:
    name: leapp-upgrade
    state: present

- name: "Install the leapp data package for the specified upgrade distro"
  yum:
    name: "leapp-data-{{ distro }}"
    state: present

- name: "Run a Pre-Upgrade check"
  shell: leapp preupgrade
  #register: preupgrade
  #failed_when: preupgrade.rc >= 2
  #failed_when: '"END OF REPORT" not in preupgrade.stdout'
  #no_log: true
