---
# Rocky Linux tasks file for ansible-role-elevate

- name: "Set a fact for a filtered list of interfaces"
  set_fact:
    filtered_interfaces: >-
      {{
        ansible_interfaces
        | reject('match', '^lo$')
        | reject('match', '^tun*')
        | list
      }}

- name: "Check for the existence of /etc/sysconfig/network-scripts/ifcfg-eno1"
  find:
    path: /etc/sysconfig/network-scripts
    patterns:
      - "ifcfg-en*"
  register: ifcfg

- name: "Convert network-scripts to NetworkManager format"
  shell: nmcli connection migrate {{ item }}
  with_items: "{{ filtered_interfaces }}"
  when:
    - ifcfg.matched != '0'
    - ansible_distribution_major_version == '8'

- name: "Copy OpenVPN configs to /etc/openvpn/client directory"
  copy:
    src: /etc/openvpn/
    dest: /etc/openvpn/client/
    remote_src: true
  when:
    - ansible_distribution_major_version == '8'

- name: "Add a Data Cipher to the OpenVPN config"
  lineinfile:
    path: /etc/openvpn/client/client.conf
    line: data-ciphers AES-256-CBC
    insertafter: EOF
    state: present
  when:
    - ansible_distribution_major_version == '8'
