---
# Rocky Linux tasks file for ansible-role-elevate

- name: "Check for the existence of /etc/sysconfig/network-scripts/ifcfg-eno1"
  stat:
    path: /etc/sysconfig/network-scripts/ifcfg-eno1
  register: ifcfg

- name: "Convert network-scripts to NetworkManager format"
  shell: nmcli connection migrate
  when:
    - ifcfg.stat.exists
    - ansible_distribution_major_version == '8'
