---
# Rocky Linux tasks file for ansible-role-elevate

- name: "Convert network-scripts to NetworkManager format"
  shell: nmcli connection migrate
  when:
    - ansible_distribution_major_version == '8'

