---
# BTRFS Fix tasks file for ansible-role-elevate

# https://access.redhat.com/solutions/7020130
- name: "Check for mounted btrfs filesystems in /proc/mounts"
  shell: cat /proc/mounts | grep -i btrfs
  register: btrfs_mounts_proc
  #failed_when: '"" not in btrfs_mounts_proc'
  ignore_errors: yes

- name: "Set fact for found btrfs filesystems in /proc/mounts"
  set_fact:
    btrfs_proc: true
  when:
    - btrfs_mounts_proc.rc == 0 or btrfs_mounts_proc.stdout != ""

- name: "Debug mounted btrfs filesystems in /proc/mounts"
  fail:
    msg: "Mounted btrfs filesystems: {{ btrfs_mounts_proc.stdout_lines }}"
  when:
    - btrfs_mounts_proc.rc == 0 or btrfs_mounts_proc.stdout != ""

#- name: "Check for mounted btrfs filesystems with findmnt"
#  command: findmnt | grep -i btrfs
#  register: btrfs_mounts_findmnt
#  ignore_errors: yes

#- name: "Set fact for found btrfs filesystems with findmnt"
#  set_fact:
#    btrfs_findmnt: true
#  when:
#    - btrfs_mounts_findmnt.rc == 0 or btrfs_mounts_findmnt.stdout != ""

#- name: "Debug mounted btrfs filesystems with findmnt"
#  fail:
#    msg: "Mounted btrfs filesystems: {{ btrfs_mounts_findmnt.stdout_lines }}"
#  when:
#    - btrfs_mounts_findmnt.rc == 0 or btrfs_mounts_findmnt.stdout != ""

- name: "Remove btrfs-progs if no btrfs mounts found (yum)"
  yum:
    name: btrfs-progs
    state: absent
  when:
    - ansible_facts['pkg_mgr'] == 'yum'
    - btrfs_proc is not defined or not btrfs_proc
    #- btrfs_findmnt is not defined or not btrfs_findmnt

- name: "Remove btrfs-progs if no btrfs mounts found (dnf)"
  dnf:
    name: btrfs-progs
    state: absent
  when:
    - ansible_facts['pkg_mgr'] == 'dnf'
    - btrfs_proc is not defined or not btrfs_proc
    #- btrfs_findmnt is not defined or not btrfs_findmnt
